### ISSUE TITLE
Gulp watch cancels if Jade encounters an error

### ISSUE THREAD

**Issue by spaceemotion** [CREEATION/laravel-elixir-jade#3]
Whenever I compile a jade template that has an error in it, gulp watch exits out completely and needs to be restarted. Other plugins (like the LESS-Compiler) do not do this. Is there a way to catch the error and let the watch script run? Thanks in advance!

**Comment by CREEATION** [comment]
Hello again!
Sure, [gulp-plumber](https://www.npmjs.com/package/gulp-plumber) to the rescue :)

**Comment by spaceemotion** [comment]
Okay, so the plumbing works now. How would I go about updating your project then? I had to add the `.pipe(plumber())` part directly into your source code… When I update the dependencies the changes would be gone.

**Comment by CREEATION** [comment]
Oh, you're right.
To be honest I recently dropped Laravel Elixir in favour of gulp from the Laravel projects I'm working on, because, as you just encountered yourself now, it's in the hands of the plugin's creator to update and add something like this.
Using gulp itself directly solves this issue and you're free to do whatever you want without having to rely on others. (and it's much more flexible, too)
I hope I can update this with `gulp-plumber` added tomorrow or so.
Thanks for your input!

**Comment by spaceemotion** [comment]
No problem! Thanks for the wonderful wrapper ;)

**Comment by CREEATION** [comment]
Updated!
